server:
  port: 8080

spring:
 application:
  name: gateway

zuul:
  ignoredHeaders:
  routes:
    first:
      sensitiveHeaders:
      url: http://localhost:8081
    second:
      sensitiveHeaders:
      url: http://localhost:8082


