spring:
  application:
    name: first
server:
  port: 8081

  cloud:
    config:
      uri: http://localhost:8888
eureka:
  client:
    smsService-url:
      defaultZone: http://localhost:8761/eureka

info:
  first:
    rest:
      version: /api/v1