spring:
 profiles:
  application:
    name: config-server
  active: native
 cloud:
   config:
     server:
       native:
         search-locations: classpath:/common-config

eureka:
  client:
    smsService-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8888
